formatter: "md"

version: ">= 0.13.0, < 1.0.0"

sections:
  hide:
    - providers

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    # GCP instance configuration

    Module to Deploy Google Compute Engine instance.

    {{ .Content }}

    ## Running

    To call this module, include in your tf configuration:

    ```terraform

    module "vm" {
      source       = "../modules/vm"
      name         = "demo-machine"
      network_name = "my-vpc-network-name" 
      subnet_name  = "my-vpc-subnet-name"
      image        = data.image 
    }

    ```

    ---
    \- maintained by: KJone1

    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
